version: 2.1
jobs:
  build_deploy_master:
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: npm i && cd functions && npm i
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: build Client and Functions
          command: npm run build
      - run:
          name: deploy to Firebase Hosting and Functions
          command: ./node_modules/.bin/firebase deploy --token "version: 2.1
jobs:
  build_deploy_master:
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: npm i && cd functions && npm i
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: build Client and Functions
          command: npm run build
      - run:
          name: deploy to Firebase Hosting and Functions
          command: ./node_modules/.bin/firebase deploy --token "version: 2.1
jobs:
  build_deploy_master:
    docker:
      - image: circleci/node:10.16.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
            - v1-dependencies-
      - run:
          name: npm install
          command: npm i && cd functions && npm i
      - save_cache:
          paths:
            - node_modules
            - functions/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
      - run:
          name: build Client and Functions
          command: npm run build
      - run:
          name: deploy to Firebase Hosting and Functions
          command: ./node_modules/.bin/firebase deploy --token "1//0eI6UNf73xnx4CgYIARAAGA4SNwF-L9IrRUS2Is89yGL89HH7kYajCXwqSLBTAbC4RfuV1dC874c4YM9JV2tVV6F21E69g-SyYPM"

workflows:
  version: 2.1
  build_deploy_master:
    jobs:
      - build_deploy_master:
          filters:
            branches:
              only: master"

workflows:
  version: 2.1
  build_deploy_master:
    jobs:
      - build_deploy_master:
          filters:
            branches:
              only: master"

workflows:
  version: 2.1
  build_deploy_master:
    jobs:
      - build_deploy_master:
          filters:
            branches:
              only: master